name: CI

on:
  push:
    branches:
      - master

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@alborea'
      - name: Building app
        run: npm install && npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_PAT }}
      - name: Running test
        run: npm run test
        env:
          EMAIL_TYPE: 'SMTP'
          EMAIL_HOST: ${{secrets.EMAIL_HOST}}
          EMAIL_PORT: ${{secrets.EMAIL_PORT}}
          EMAIL_USER: ${{secrets.EMAIL_USER}}
          EMAIL_PASS: ${{secrets.EMAIL_PASS}}
      - name: Publishing
        run: npm publish
